// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8M9-eNhYGwhZDq8YctpwwAtN-OovC6E',
    appId: '1:281377011187:web:3133540dfdcc460a154e86',
    messagingSenderId: '281377011187',
    projectId: 'mensa-scolastica',
    authDomain: 'mensa-scolastica.firebaseapp.com',
    storageBucket: 'mensa-scolastica.firebasestorage.app',
    measurementId: 'G-85E8D58KHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB11s9gRJzsDv_WB0kgNoztf_lBZwts9FQ',
    appId: '1:281377011187:android:54565425261c8a72154e86',
    messagingSenderId: '281377011187',
    projectId: 'mensa-scolastica',
    storageBucket: 'mensa-scolastica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_VIsUl-u_JOLg2U8sXBkv-MvlqNAYsc',
    appId: '1:281377011187:ios:87f385bf08d2dc82154e86',
    messagingSenderId: '281377011187',
    projectId: 'mensa-scolastica',
    storageBucket: 'mensa-scolastica.firebasestorage.app',
    iosBundleId: 'com.example.mensaScolastica',
  );
}
